In [170]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import KFold
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder


In [171]:
df=pd.read_csv("/content/forestfires.csv")

In [172]:
df.head()

month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  ...  monthfeb  \
0   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0  ...         0   
1   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0  ...         0   
2   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0  ...         0   
3   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2  ...         0   
4   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0  ...         0   

   monthjan  monthjul  monthjun  monthmar  monthmay  monthnov  monthoct  \
0         0         0         0         1         0         0         0   
1         0         0         0         0         0         0         1   
2         0         0         0         0         0         0         1   
3         0         0         0         1         0         0         0   
4         0         0         0         1         0         0         0   

   monthsep  size_category  
0         0          small  
1         0          small  
2         0          small  
3         0          small  
4         0          small  

[5 rows x 31 columns]

# **EDA**

In [173]:
df.columns

Index(['month', 'day', 'FFMC', 'DMC', 'DC', 'ISI', 'temp', 'RH', 'wind',
       'rain', 'area', 'dayfri', 'daymon', 'daysat', 'daysun', 'daythu',
       'daytue', 'daywed', 'monthapr', 'monthaug', 'monthdec', 'monthfeb',
       'monthjan', 'monthjul', 'monthjun', 'monthmar', 'monthmay', 'monthnov',
       'monthoct', 'monthsep', 'size_category'],
      dtype='object')

In [174]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 517 entries, 0 to 516
Data columns (total 31 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   month          517 non-null    object 
 1   day            517 non-null    object 
 2   FFMC           517 non-null    float64
 3   DMC            517 non-null    float64
 4   DC             517 non-null    float64
 5   ISI            517 non-null    float64
 6   temp           517 non-null    float64
 7   RH             517 non-null    int64  
 8   wind           517 non-null    float64
 9   rain           517 non-null    float64
 10  area           517 non-null    float64
 11  dayfri         517 non-null    int64  
 12  daymon         517 non-null    int64  
 13  daysat         517 non-null    int64  
 14  daysun         517 non-null    int64  
 15  daythu         517 non-null    int64  
 16  daytue         517 non-null    int64  
 17  daywed         517 non-null    int64  
 18  monthapr  

In [175]:
df.isna().sum()

month            0
day              0
FFMC             0
DMC              0
DC               0
ISI              0
temp             0
RH               0
wind             0
rain             0
area             0
dayfri           0
daymon           0
daysat           0
daysun           0
daythu           0
daytue           0
daywed           0
monthapr         0
monthaug         0
monthdec         0
monthfeb         0
monthjan         0
monthjul         0
monthjun         0
monthmar         0
monthmay         0
monthnov         0
monthoct         0
monthsep         0
size_category    0
dtype: int64

In [176]:
df=df.drop(columns=['dayfri', 'daymon', 'daysat', 'daysun', 'daythu','daytue', 'daywed', 'monthapr', 'monthaug', 'monthdec', 'monthfeb','monthjan', 'monthjul', 'monthjun', 'monthmar', 'monthmay', 'monthnov','monthoct', 'monthsep',])

In [177]:
df.head()

month  day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area size_category
0   mar  fri  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0         small
1   oct  tue  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0         small
2   oct  sat  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0         small
3   mar  fri  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0         small
4   mar  sun  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0         small

In [178]:


month_data={'month':{'jan':1,'feb':2,'mar':3,'apr':4,'may':5,'jun':6,'jul':7,'aug':8,'sep':9,'oct':10,'nov':11,'dec':12}}
df.replace(month_data,inplace=True)

day_data={'day':{'mon':1,'tue':2,'wed':3,'thu':4,'fri':5,'sat':6,'sun':'7'}}
df.replace(day_data,inplace=True)

df.size_category.replace(('small','large'),(1,0),inplace=True)

In [179]:
df.head()

month day  FFMC   DMC     DC  ISI  temp  RH  wind  rain  area  \
0      3   5  86.2  26.2   94.3  5.1   8.2  51   6.7   0.0   0.0   
1     10   2  90.6  35.4  669.1  6.7  18.0  33   0.9   0.0   0.0   
2     10   6  90.6  43.7  686.9  6.7  14.6  33   1.3   0.0   0.0   
3      3   5  91.7  33.3   77.5  9.0   8.3  97   4.0   0.2   0.0   
4      3   7  89.3  51.3  102.2  9.6  11.4  99   1.8   0.0   0.0   

   size_category  
0              1  
1              1  
2              1  
3              1  
4              1

In [180]:
df['size_category'].unique()

array([1, 0])

In [181]:
df.columns

Index(['month', 'day', 'FFMC', 'DMC', 'DC', 'ISI', 'temp', 'RH', 'wind',
       'rain', 'area', 'size_category'],
      dtype='object')

In [182]:
sc=StandardScaler()
df[['month', 'day', 'FFMC', 'DMC', 'DC', 'ISI', 'temp', 'RH', 'wind','rain', 'area']]=sc.fit_transform(df[['month', 'day', 'FFMC', 'DMC', 'DC', 'ISI', 'temp', 'RH', 'wind','rain', 'area']])

In [183]:
df.head()

month       day      FFMC       DMC        DC       ISI      temp  \
0 -1.968443  0.357721 -0.805959 -1.323326 -1.830477 -0.860946 -1.842640   
1  1.110120 -1.090909 -0.008102 -1.179541  0.488891 -0.509688 -0.153278   
2  1.110120  0.840597 -0.008102 -1.049822  0.560715 -0.509688 -0.739383   
3 -1.968443  0.357721  0.191362 -1.212361 -1.898266 -0.004756 -1.825402   
4 -1.968443  1.323474 -0.243833 -0.931043 -1.798600  0.126966 -1.291012   

         RH      wind      rain     area  size_category  
0  0.411724  1.498614 -0.073268 -0.20202              1  
1 -0.692456 -1.741756 -0.073268 -0.20202              1  
2 -0.692456 -1.518282 -0.073268 -0.20202              1  
3  3.233519 -0.009834  0.603155 -0.20202              1  
4  3.356206 -1.238940 -0.073268 -0.20202              1

# **Building SVM**

In [184]:
x=df.iloc[:,0:11]
y=df.iloc[:,11]
y

0      1
1      1
2      1
3      1
4      1
      ..
512    0
513    0
514    0
515    1
516    1
Name: size_category, Length: 517, dtype: int64

In [189]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.20,random_state=12,stratify=y)

# **Model Training**

In [190]:
model=SVC(kernel='rbf',C=15)

In [191]:
print(xtrain.shape)
print(xtest.shape)
print(ytrain.shape)
print(ytest.shape)

(413, 11)
(104, 11)
(413,)
(104,)


In [192]:
model.fit(xtrain,ytrain)

SVC(C=15)

# **Model Testing**

In [193]:
ypred=model.predict(xtest)

In [194]:
ypred

array([1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [195]:
y_train_pred=model.predict(xtrain)
y_train_pred

array([1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1,

# **Model Evaluation**

In [197]:
print(confusion_matrix(ytrain,y_train_pred))

[[ 97  14]
 [  1 301]]


In [198]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.88      0.82      0.85        28
           1       0.94      0.96      0.95        76

    accuracy                           0.92       104
   macro avg       0.91      0.89      0.90       104
weighted avg       0.92      0.92      0.92       104



In [199]:
print(confusion_matrix(ytest,ypred))

[[23  5]
 [ 3 73]]


In [200]:
print(classification_report(ytrain,y_train_pred))

              precision    recall  f1-score   support

           0       0.99      0.87      0.93       111
           1       0.96      1.00      0.98       302

    accuracy                           0.96       413
   macro avg       0.97      0.94      0.95       413
weighted avg       0.96      0.96      0.96       413



# Training Accuracy:96%
# Testing Accuracy:92%